module.exports = [
  {
    text: "404 Media",
    tags: ["high-volume", "news", "technology"],
    xmlUrl: "https://www.404media.co/rss/",
    htmlUrl: "https://www.404media.co/",
  },
  {
    text: "A Very Good Blog",
    author: "Keenan",
    xmlUrl: "https://gkeenan.co/avgb/feed.xml",
    htmlUrl: "https://gkeenan.co/avgb",
  },
  {
    text: "Adactio",
    author: "Jeremy Keith",
    authorWiki: "Jeremy Keith (web developer)",
    tags: ["indieweb"],
    xmlUrl: "https://adactio.com/rss/",
    htmlUrl: "https://adactio.com/",
  },
  {
    text: "AINT",
    author: "John Mark",
    tags: ["technology"],
    xmlUrl: "https://aint.johnmark.org/feed/",
    htmlUrl: "https://aint.johnmark.org/",
  },
  {
    author: "Anil Dash",
    authorWiki: "Anil Dash",
    tags: ["web"],
    xmlUrl: "https://feeds.dashes.com/AnilDash",
    htmlUrl: "https://dashes.com/anil/",
  },
  {
    author: "Aram Zucker-Scharff",
    xmlUrl: "https://aramzs.xyz/writing/feed.xml",
    htmlUrl: "https://aramzs.xyz/",
  },
  {
    author: "Ben Werdm\u00fcller",
    tags: ["indieweb", "technology", "web"],
    xmlUrl: "https://werd.io/?_t=rss",
    htmlUrl: "https://werd.io/",
  },
  {
    text: "BirchTree",
    author: "Matt Birchler",
    tags: ["newsletter"],
    xmlUrl: "https://birchtree.me/rss/",
    htmlUrl: "https://birchtree.me/",
  },
  {
    author: "Bob Sassone",
    xmlUrl: "https://sassone.wordpress.com/feed/",
    htmlUrl: "http://sassone.wordpress.com/",
  },
  {
    text: "cabel.com",
    author: "Cabel Sasser",
    xmlUrl: "https://cabel.com/feed/",
    htmlUrl: "https://cabel.com",
  },
  {
    text: "Coding Horror",
    author: "Jeff Atwood",
    authorWiki: "Jeff Atwood",
    xmlUrl: "https://blog.codinghorror.com/rss/",
    htmlUrl: "https://blog.codinghorror.com/",
  },
  {
    text: "computers are bad",
    tags: ["technology"],
    xmlUrl: "https://computer.rip/rss.xml",
    htmlUrl: "https://computer.rip/",
  },
  {
    author: "Dan Luu",
    xmlUrl: "https://danluu.com/atom.xml",
    htmlUrl: "http://danluu.com/",
  },
  {
    text: "Dan York Media",
    author: "Dan York",
    xmlUrl: "https://danyork.me/feed/",
    htmlUrl: "https://danyork.me/",
  },
  {
    text: "Daring Fireball",
    author: "John Gruber",
    authorWiki: "John Gruber",
    tags: ["high-volume", "news", "technology"],
    xmlUrl: "https://daringfireball.net/feeds/main",
    htmlUrl: "https://daringfireball.net/",
  },
  {
    text: "Dirty Bubble Media",
    author: "James Block",
    tags: ["crypto", "newsletter", "Substack"],
    xmlUrl: "https://www.dirtybubblemedia.com/feed",
    htmlUrl: "https://www.dirtybubblemedia.com/",
  },
  {
    text: "Disconnect",
    author: "Paris Marx",
    authorWiki: "Paris Marx",
    tags: ["newsletter", "technology"],
    xmlUrl: "https://disconnect.blog/rss/",
    htmlUrl: "https://disconnect.blog/",
  },
  {
    text: "Doc Searls Weblog",
    author: "Doc Searls",
    authorWiki: "Doc Searls",
    xmlUrl: "https://doc.searls.com/feed/",
    htmlUrl: "https://doc.searls.com/",
  },
  {
    text: "DSHR's Blog",
    author: "David S. H. Rosenthal",
    authorWiki: "David S. H. Rosenthal",
    tags: ["crypto", "technology"],
    xmlUrl: "https://blog.dshr.org/feeds/posts/default",
    htmlUrl: "https://blog.dshr.org/",
  },
  {
    text: "Where's Your Ed At",
    author: "Ed Zitron",
    tags: ["newsletter", "technology"],
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://www.wheresyoured.at/",
  },
  {
    text: "internet website lol",
    author: "Erin Kissane",
    xmlUrl: "https://erinkissane.com/feed.rss",
    htmlUrl: "https://erinkissane.com/",
  },
  {
    author: "Ethan Marcotte",
    xmlUrl: "https://ethanmarcotte.com/wrote/feed.xml",
    htmlUrl: "https://ethanmarcotte.com/",
  },
  {
    author: "Evan Boehs",
    tags: ["technology"],
    xmlUrl: "https://boehs.org/in/blog.xml",
    htmlUrl: "https://boehs.org/",
  },
  {
    text: "fLaMEdFURY",
    xmlUrl: "https://flamedfury.com/feed.xml",
    htmlUrl: "https://flamedfury.com/",
  },
  {
    text: "Flaming Hydra",
    tags: ["high-volume", "news"],
    xmlUrl: "https://flaminghydra.com/rss/",
    htmlUrl: "https://flaminghydra.com/",
  },
  {
    text: "FlowingData",
    author: "Nathan Yau",
    xmlUrl: "https://flowingdata.com/feed",
    htmlUrl: "http://flowingdata.com/",
  },
  {
    text: "from jason",
    author: "Jason Velazquez",
    tags: ["technology", "web"],
    xmlUrl: "https://www.fromjason.xyz/feed/feed.xml",
    htmlUrl: "https://fromjason.xyz/",
  },
  {
    text: "Fudge Sunday",
    author: "Jay Cuthrell",
    xmlUrl: "https://fudge.org/rss.xml",
    htmlUrl: "https://fudge.org/",
  },
  {
    text: "Garbage Day",
    tags: ["news", "newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/owMwaGYU36.xml",
    htmlUrl: "https://www.garbageday.email/",
  },
  {
    text: "gilest.org",
    author: "Giles Turnbull",
    xmlUrl: "https://gilest.org/feed/index.xml",
    htmlUrl: "https://gilest.org/",
  },
  {
    text: "Horrific/Terrific",
    author: "Georgia Iacovou",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://www.horrific-terrific.tech/feed",
    htmlUrl: "https://www.horrific-terrific.tech",
  },
  {
    text: "IndieNews English",
    tags: ["aggregator", "indieweb"],
    xmlUrl:
      "https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fnews.indieweb.org%2Fen",
    htmlUrl: "https://aaronparecki.com/",
  },
  {
    text: "Infinite Wishes",
    author: "Emma Humphries",
    xmlUrl: "https://emmas.site/blog/atom.xml",
    htmlUrl: "http://emmas.site/",
  },
  {
    text: "Interconnected",
    author: "Matt Webb",
    xmlUrl: "https://interconnected.org/home/feed",
    htmlUrl: "https://interconnected.org/home",
  },
  {
    author: "Jacob Silverman",
    tags: ["newsletter", "Substack", "technology"],
    xmlUrl: "https://www.jacobsilverman.com/feed",
    htmlUrl: "https://www.jacobsilverman.com/",
  },
  {
    author: "James Cridland",
    tags: ["indieweb"],
    xmlUrl: "https://james.cridland.net/index.xml",
    htmlUrl: "https://james.cridland.net/",
  },
  {
    author: "James G",
    tags: ["indieweb"],
    xmlUrl:
      "https://granary.io/url?input=html&output=rss&url=https://jamesg.blog",
    htmlUrl: "https://jamesg.blog/",
  },
  {
    text: "@Westenberg",
    author: "Joan Westenberg",
    xmlUrl: "https://www.joanwestenberg.com/rss/",
    htmlUrl: "https://www.joanwestenberg.com/",
  },
  {
    author: "Josh Collinsworth",
    tags: ["technology"],
    xmlUrl: "https://joshcollinsworth.com/rss",
    htmlUrl: "https://joshcollinsworth.com/",
  },
  {
    author: "Juha-Matti Santala",
    tags: ["technology"],
    xmlUrl: "https://hamatti.org/feed/feed.xml",
    htmlUrl: "https://hamatti.org/",
  },
  {
    author: "Justin Pot",
    tags: ["technology"],
    xmlUrl: "https://justinpot.com/feed/",
    htmlUrl: "https://justinpot.com/",
  },
  {
    text: "jwz",
    author: "Jamie Zawinski",
    authorWiki: "Jamie Zawinski",
    tags: ["technology"],
    xmlUrl: "https://cdn.jwz.org/blog/feed/",
    htmlUrl: "https://www.jwz.org/blog/",
  },
  {
    author: "Kev Quirk",
    tags: ["indieweb"],
    xmlUrl: "https://kevquirk.com/feed",
    htmlUrl: "https://kevquirk.com/",
  },
  {
    text: "Live Laugh Blog",
    author: "Jenn Schiffer",
    xmlUrl: "https://livelaugh.blog/rss.xml",
    htmlUrl: "https://livelaugh.blog/",
  },
  {
    text: "LOL (lots of links)",
    author: "Annie Rauwerda",
    authorWiki: "Annie Rauwerda",
    tags: ["Wikipedia"],
    xmlUrl: "https://lotsoflinks.substack.com/feed",
    htmlUrl: "https://lotsoflinks.substack.com/",
  },
  {
    text: "Ludicity",
    author: "Nikhil Suresh",
    tags: ["technology"],
    xmlUrl: "https://ludic.mataroa.blog/rss/",
    htmlUrl: "https://ludic.mataroa.blog/",
  },
  {
    text: "lyonheart.us",
    author: "Matthew Lyon",
    xmlUrl: "https://lyonheart.us/index.xml",
    htmlUrl: "https://lyonheart.us/",
  },
  {
    author: "Tom MacWright",
    xmlUrl: "https://macwright.com/micro/rss.xml",
    htmlUrl: "https://macwright.com/",
  },
  {
    author: "Maggie Appleton",
    xmlUrl: "https://maggieappleton.com/rss.xml",
    htmlUrl: "https://maggieappleton.com/",
  },
  {
    author: "Manuel Moreale",
    xmlUrl: "https://manuelmoreale.com/feed/rss",
    htmlUrl: "https://manuelmoreale.com/",
  },
  {
    text: "Matthias Ott",
    author: "Matthias Ott",
    xmlUrl: "https://matthiasott.com/rss",
    htmlUrl: "https://matthiasott.com/",
  },
  {
    text: "Mind and Iron",
    author: "Steven Zeitchik",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://mindandiron.substack.com/feed",
    htmlUrl: "https://mindandiron.substack.com/",
  },
  {
    text: "ongoing",
    author: "Tim Bray",
    authorWiki: "Tim Bray",
    tags: ["indieweb"],
    xmlUrl: "https://www.tbray.org/ongoing/ongoing.atom",
    htmlUrl: "https://www.tbray.org/ongoing/",
  },
  {
    text: "Own Your Web",
    author: "Matthias Ott",
    tags: ["newsletter", "web"],
    xmlUrl: "https://buttondown.email/ownyourweb/rss",
    htmlUrl: "https://buttondown.email/ownyourweb",
  },
  {
    text: "Paul's Dev Notes",
    author: "Paul Frazee",
    tags: ["technology"],
    xmlUrl: "https://www.pfrazee.com/feed.xml",
    htmlUrl: "https://pfrazee.com/blog",
  },
  {
    text: "Pixel Envy",
    author: "Nick Heer",
    xmlUrl: "https://pxlnv.com/feed/",
    htmlUrl: "http://pxlnv.com/",
  },
  {
    text: "Pluralistic",
    author: "Cory Doctorow",
    authorWiki: "Cory Doctorow",
    xmlUrl: "https://pluralistic.net/feed/",
    htmlUrl: "https://pluralistic.net/",
  },
  {
    text: "Read Max",
    author: "Max Read",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://maxread.substack.com/feed/",
    htmlUrl: "https://maxread.substack.com/",
  },
  {
    text: "reb00ted",
    author: "Johannes Ernst",
    xmlUrl: "https://reb00ted.org/index.xml",
    htmlUrl: "https://reb00ted.org/",
  },
  {
    text: "rendezvous with cassidoo",
    author: "Cassidy Williams",
    tags: ["newsletter", "technology"],
    xmlUrl: "https://buttondown.email/cassidoo/rss",
    htmlUrl: "https://buttondown.email/cassidoo",
  },
  {
    text: "Richard Felix",
    author: "Richard Felix",
    xmlUrl: "https://richardfelix.com/feed.xml",
    htmlUrl: "https://richardfelix.com/",
  },
  {
    text: "Ricky Mondello",
    author: "Ricky Mondello",
    xmlUrl: "https://rmondello.com/feed/",
    htmlUrl: "https://rmondello.com/",
  },
  {
    text: "Schneier on Security",
    author: "Bruce Schneier",
    authorWiki: "Bruce Schneier",
    tags: ["security", "technology"],
    xmlUrl: "https://www.schneier.com/blog/index.rdf",
    htmlUrl: "https://www.schneier.com/blog/",
  },
  {
    author: "Scott Hanselman",
    xmlUrl: "https://www.hanselman.com/blog/feed/rss",
    htmlUrl: "https://www.hanselman.com/blog/",
  },
  {
    text: "Scripting News",
    author: "Dave Winer",
    authorWiki: "Dave Winer",
    tags: ["high-volume"],
    xmlUrl: "http://scripting.com/rss.xml",
    htmlUrl: "http://scripting.com/",
  },
  {
    text: "Sentencing Law and Policy",
    author: "Douglas A. Berman",
    tags: ["law"],
    xmlUrl:
      "https://sentencing.typepad.com/sentencing_law_and_policy/index.rdf",
    htmlUrl: "https://sentencing.typepad.com/sentencing_law_and_policy/",
  },
  {
    author: "Simon Willison",
    authorWiki: "Simon Willison",
    tags: ["technology"],
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "http://simonwillison.net/",
  },
  {
    text: "snarfed.org",
    author: "Ryan Barrett",
    tags: ["indieweb"],
    xmlUrl: "https://snarfed.org/feed",
    htmlUrl: "https://snarfed.org/",
  },
  {
    text: "Songs on the Security of Networks",
    author: "Micha\u0142 “rysiek” Wo\u017aniak",
    tags: ["technology"],
    xmlUrl: "https://rys.io/feed.rss",
    htmlUrl: "https://rys.io/",
  },
  {
    text: "starbreaker.org",
    author: "Matthew Graybosch",
    xmlUrl: "https://starbreaker.org/feeds/everything.xml",
    htmlUrl: "https://starbreaker.org/",
  },
  {
    text: "Subconscious",
    tags: ["newsletter", "substack"],
    xmlUrl: "https://subconscious.substack.com/feed",
    htmlUrl: "https://subconscious.substack.com/",
  },
  {
    text: "Take on Rules",
    author: "Jeremy Friesen",
    tags: ["technology"],
    xmlUrl: "https://takeonrules.com/index.xml",
    htmlUrl: "https://takeonrules.com/",
  },
  {
    author: "Tantek \u00c7elik",
    authorWiki: "Tantek \u00c7elik",
    tags: ["indieweb"],
    xmlUrl: "https://tantek.com/updates.atom",
    htmlUrl: "https://tantek.com/",
  },
  {
    text: "Techdirt",
    tags: ["high-volume", "news"],
    xmlUrl: "https://www.techdirt.com/techdirt_rss.xml",
    htmlUrl: "https://www.techdirt.com/",
  },
  {
    author: "Terence Eden",
    tags: ["indieweb"],
    xmlUrl: "https://shkspr.mobi/blog/feed/atom/",
    htmlUrl: "https://shkspr.mobi/blog",
  },
  {
    text: "The Dig",
    author: "Francine McKenna",
    authorWiki: "Francine McKenna",
    tags: ["crypto", "finance", "newsletter", "Substack"],
    xmlUrl: "https://thedig.substack.com/feed",
    htmlUrl: "https://thedig.substack.com/",
  },
  {
    text: "The Future, Now and Then",
    author: "Dave Karpf",
    tags: ["newsletter", "Substack", "technology"],
    xmlUrl: "https://davekarpf.substack.com/feed",
    htmlUrl: "https://davekarpf.substack.com/",
  },
  {
    text: "The Handbasket",
    author: "Marisa Kabas",
    tags: ["news", "newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/40ZQ7CSldT.xml",
    htmlUrl: "https://www.thehandbasket.co/",
  },
  {
    text: "The History of the Web",
    author: "Jay Hoffmann",
    tags: ["web"],
    xmlUrl: "https://thehistoryoftheweb.com/feed/",
    htmlUrl: "https://thehistoryoftheweb.com/",
  },
  {
    text: "The Popehat Report",
    author: "Ken White",
    authorWiki: "Popehat",
    tags: ["law", "newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/6QXMLvJf2y.xml",
    htmlUrl: "https://www.popehat.com/",
  },
  {
    text: "The Present Age",
    author: "Parker Molloy",
    authorWiki: "Parker Molloy",
    tags: ["politics", "newsletter", "Substack"],
    xmlUrl: "https://www.readtpa.com/feed",
    htmlUrl: "https://www.readtpa.com/",
  },
  {
    text: "The Public Domain Review",
    tags: ["archives"],
    xmlUrl: "https://publicdomainreview.org/rss.xml",
    htmlUrl: "https://publicdomainreview.org/",
  },
  {
    text: "The Wikipedian",
    author: "William Beutler",
    tags: ["newsletter", "Substack", "Wikipedia"],
    xmlUrl: "https://thewikipedian.substack.com/feed",
    htmlUrl: "https://www.thewikipedian.net/",
  },
  {
    text: "This Week in the IndieWeb",
    tags: ["aggregator", "indieweb"],
    xmlUrl: "https://indieweb.org/this-week/feed.xml",
    htmlUrl: "https://indieweb.org/this-week",
  },
  {
    text: "Today in Tabs",
    author: "Rusty Foster",
    authorWiki: "Rusty Foster",
    tags: ["newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/ZRiesnGI0u.xml",
    htmlUrl: "https://www.todayintabs.com/",
  },
  {
    text: "Mind Garden",
    author: "Tracy Durnell",
    xmlUrl: "https://tracydurnell.com/feed/",
    htmlUrl: "https://tracydurnell.com/",
  },
  {
    text: "Untangled",
    author: "Charley Johnson",
    tags: ["newsletter", "Substack", "technology"],
    xmlUrl: "https://untangled.substack.com/feed",
    htmlUrl: "https://untangled.substack.com/",
  },
  {
    text: "Waxy.org",
    author: "Andy Baio",
    authorWiki: "Andy Baio",
    tags: ["web"],
    xmlUrl: "https://waxy.org/feed/",
    htmlUrl: "https://waxy.org",
  },
  {
    text: "Writings and rehearsals by Nathan Schneider",
    author: "Nathan Schneider",
    authorWiki: "Nathan Schneider",
    xmlUrl: "https://nathanschneider.info/feed/",
    htmlUrl: "https://nathanschneider.info/",
  },
];
