module.exports = [
  {
    text: "Adactio",
    author: "Jeremy Keith",
    authorWiki: "Jeremy Keith (web developer)",
    tags: ["indieweb"],
    xmlUrl: "https://adactio.com/rss/",
    htmlUrl: "https://adactio.com/",
  },
  {
    author: "Anil Dash",
    authorWiki: "Anil Dash",
    tags: ["web"],
    xmlUrl: "https://feeds.dashes.com/AnilDash",
    htmlUrl: "https://dashes.com/anil/",
  },
  {
    author: "Ben Werdm\u00fcller",
    xmlUrl: "https://werd.io/?_t=rss",
    htmlUrl: "https://werd.io/",
  },
  {
    text: "BirchTree",
    author: "Matt Birchler",
    tags: ["newsletter"],
    xmlUrl: "https://birchtree.me/rss/",
    htmlUrl: "https://birchtree.me/",
  },
  {
    text: "cabel.com",
    author: "Cabel Sasser",
    xmlUrl: "https://cabel.com/feed/",
    htmlUrl: "https://cabel.com",
  },
  {
    text: "Coding Horror",
    author: "Jeff Atwood",
    authorWiki: "Jeff Atwood",
    xmlUrl: "https://blog.codinghorror.com/rss/",
    htmlUrl: "https://blog.codinghorror.com/",
  },
  {
    text: "Court Watch",
    author: "Seamus Hughes",
    tags: ["law", "newsletter", "Substack"],
    xmlUrl: "https://seamushughes.substack.com/feed",
    htmlUrl: "https://seamushughes.substack.com/",
  },
  {
    author: "Dan Luu",
    xmlUrl: "https://danluu.com/atom.xml",
    htmlUrl: "http://danluu.com/",
  },
  {
    text: "Dan York Media",
    author: "Dan York",
    xmlUrl: "https://danyork.me/feed/",
    htmlUrl: "https://danyork.me/",
  },
  {
    text: "Daring Fireball",
    author: "John Gruber",
    authorWiki: "John Gruber",
    xmlUrl: "https://daringfireball.net/feeds/main",
    htmlUrl: "https://daringfireball.net/",
  },
  {
    text: "Dirty Bubble Media",
    author: "James Block",
    tags: ["crypto", "newsletter", "Substack"],
    xmlUrl: "https://www.dirtybubblemedia.com/feed",
    htmlUrl: "https://www.dirtybubblemedia.com/",
  },
  {
    text: "Disconnect",
    author: "Paris Marx",
    authorWiki: "Paris Marx",
    tags: ["newsletter"],
    xmlUrl: "https://disconnect.blog/rss/",
    htmlUrl: "https://disconnect.blog/",
  },
  {
    text: "DSHR's Blog",
    author: "David S. H. Rosenthal",
    authorWiki: "David S. H. Rosenthal",
    tags: ["crypto", "technology"],
    xmlUrl: "https://blog.dshr.org/feeds/posts/default",
    htmlUrl: "https://blog.dshr.org/",
  },
  {
    text: "Where's Your Ed At",
    author: "Ed Zitron",
    tags: ["crypto", "newsletter", "technology"],
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://www.wheresyoured.at/",
  },
  {
    author: "Ethan Marcotte",
    xmlUrl: "https://ethanmarcotte.com/wrote/feed.xml",
    htmlUrl: "https://ethanmarcotte.com/",
  },
  {
    text: "fLaMEdFURY",
    xmlUrl: "https://flamedfury.com/feed.xml",
    htmlUrl: "https://flamedfury.com/",
  },
  {
    text: "Fudge Sunday",
    author: "Jay Cuthrell",
    xmlUrl: "https://fudge.org/rss.xml",
    htmlUrl: "https://fudge.org/",
  },
  {
    text: "Garbage Day",
    author: "Ryan Broderick",
    authorWiki: "Ryan Broderick",
    tags: ["newsletter", "web"],
    xmlUrl: "https://rss.beehiiv.com/feeds/99VTTjt0N1.xml",
    htmlUrl: "https://www.garbageday.email/",
  },
  {
    text: "gilest.org",
    author: "Giles Turnbull",
    xmlUrl: "https://gilest.org/feed/index.xml",
    htmlUrl: "https://gilest.org/",
  },
  {
    text: "Horrific/Terrific",
    author: "Georgia Iacovou",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://www.horrific-terrific.tech/feed",
    htmlUrl: "https://www.horrific-terrific.tech",
  },
  {
    text: "IndieNews English",
    tags: ["aggregator", "indieweb"],
    xmlUrl:
      "https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fnews.indieweb.org%2Fen",
    htmlUrl: "https://aaronparecki.com/",
  },
  {
    text: "Infinite Wishes",
    author: "Emma Humphries",
    xmlUrl: "https://emmas.site/blog/atom.xml",
    htmlUrl: "http://emmas.site/",
  },
  {
    author: "Jacob Silverman",
    tag: "newsletter, Substack, technology",
    xmlUrl: "https://www.jacobsilverman.com/feed",
    htmlUrl: "https://www.jacobsilverman.com/",
  },
  {
    author: "James Cridland",
    tag: "indieweb",
    xmlUrl: "https://james.cridland.net/index.xml",
    htmlUrl: "https://james.cridland.net/",
  },
  {
    text: "James G",
    tag: "indieweb",
    xmlUrl:
      "https://granary.io/url?input=html&output=rss&url=https://jamesg.blog",
    htmlUrl: "https://jamesg.blog/",
  },
  {
    author: "Josh Collinsworth",
    tags: ["technology"],
    xmlUrl: "https://joshcollinsworth.com/rss",
    htmlUrl: "https://joshcollinsworth.com/",
  },
  {
    text: "jwz",
    author: "Jamie Zawinski",
    authorWiki: "Jamie Zawinski",
    tags: ["technology"],
    xmlUrl: "https://cdn.jwz.org/blog/feed/",
    htmlUrl: "https://www.jwz.org/blog/",
  },
  {
    author: "Kev Quirk",
    tags: ["indieweb"],
    xmlUrl: "https://kevquirk.com/feed",
    htmlUrl: "https://kevquirk.com/",
  },
  {
    text: "Live Laugh Blog",
    author: "Jenn Schiffer",
    xmlUrl: "https://livelaugh.blog/rss.xml",
    htmlUrl: "https://livelaugh.blog/",
  },
  {
    text: "LOL (lots of links)",
    author: "Annie Rauwerda",
    authorWiki: "Annie Rauwerda",
    tags: ["Wikipedia"],
    xmlUrl: "https://lotsoflinks.substack.com/feed",
    htmlUrl: "https://lotsoflinks.substack.com/",
  },
  {
    author: "Tom MacWright",
    xmlUrl: "https://macwright.com/micro/rss.xml",
    htmlUrl: "https://macwright.com/",
  },
  {
    author: "Maggie Appleton",
    xmlUrl: "https://maggieappleton.com/rss.xml",
    htmlUrl: "https://maggieappleton.com/",
  },
  {
    text: "Money Stuff",
    author: "Matt Levine",
    authorWiki: "Matt Levine (columnist)",
    tags: ["crypto", "finance", "newsletter"],
    xmlUrl:
      "https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss",
    htmlUrl:
      "https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine",
  },
  {
    text: "Mind and Iron",
    author: "Steven Zeitchik",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://mindandiron.substack.com/feed",
    htmlUrl: "https://mindandiron.substack.com/",
  },
  {
    text: "ongoing",
    author: "Tim Bray",
    authorWiki: "Tim Bray",
    comment: "indieweb",
    xmlUrl: "https://www.tbray.org/ongoing/ongoing.atom",
    htmlUrl: "https://www.tbray.org/ongoing/",
  },
  {
    text: "Own Your Web",
    author: "Matthias Ott",
    tags: ["newsletter", "web"],
    xmlUrl: "https://buttondown.email/ownyourweb/rss",
    htmlUrl: "https://buttondown.email/ownyourweb",
  },
  {
    text: "Pixel Envy",
    author: "Nick Heer",
    xmlUrl: "https://pxlnv.com/feed/",
    htmlUrl: "http://pxlnv.com/",
  },
  {
    text: "Pluralistic: Daily links",
    author: "Cory Doctorow",
    authorWiki: "Cory Doctorow",
    xmlUrl: "https://pluralistic.net/feed/",
    htmlUrl: "https://pluralistic.net/",
  },
  {
    text: "Read Max",
    author: "Max Read",
    tags: ["newsletter", "Substack"],
    xmlUrl: "https://maxread.substack.com/feed/",
    htmlUrl: "https://maxread.substack.com/",
  },
  {
    text: "reb00ted",
    author: "Johannes Ernst",
    xmlUrl: "https://reb00ted.org/index.xml",
    htmlUrl: "https://reb00ted.org/",
  },
  {
    text: "rendezvous with cassidoo",
    author: "Cassidy Williams",
    tags: ["newsletter", "technology"],
    xmlUrl: "https://buttondown.email/cassidoo/rss",
    htmlUrl: "https://buttondown.email/cassidoo",
  },
  {
    text: "Schneier on Security",
    author: "Bruce Schneier",
    authorWiki: "Bruce Schneier",
    tags: ["security", "technology"],
    xmlUrl: "https://www.schneier.com/blog/index.rdf",
    htmlUrl: "https://www.schneier.com/blog/",
  },
  {
    author: "Scott Hanselman",
    xmlUrl: "https://www.hanselman.com/blog/feed/rss",
    htmlUrl: "https://www.hanselman.com/blog/",
  },
  {
    text: "Sentencing Law and Policy",
    author: "Douglas A. Berman",
    tags: ["law"],
    xmlUrl:
      "https://sentencing.typepad.com/sentencing_law_and_policy/index.rdf",
    htmlUrl: "https://sentencing.typepad.com/sentencing_law_and_policy/",
  },
  {
    author: "Simon Willison",
    authorWiki: "Simon Willison",
    tags: ["technology"],
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "http://simonwillison.net/",
  },
  {
    text: "snarfed.org",
    author: "Ryan Barrett",
    tags: ["indieweb"],
    xmlUrl: "https://snarfed.org/feed",
    htmlUrl: "https://snarfed.org/",
  },
  {
    text: "Songs on the Security of Networks",
    author: 'Micha\u0142 "rysiek" Wo\u017aniak',
    tags: ["technology"],
    xmlUrl: "https://rys.io/feed.rss",
    htmlUrl: "https://rys.io/",
  },
  {
    text: "Subconscious",
    tags: ["newsletter", "substack"],
    xmlUrl: "https://subconscious.substack.com/feed",
    htmlUrl: "https://subconscious.substack.com/",
  },
  {
    text: "Tantek \u00c7elik",
    author: "Tantek \u00c7elik",
    authorWiki: "Tantek \u00c7elik",
    tags: ["indieweb"],
    xmlUrl: "https://tantek.com/updates.atom",
    htmlUrl: "https://tantek.com/",
  },
  {
    text: "Tech + Economics + Humans",
    author: "Joan Westenberg",
    tags: ["newsletter", "technology"],
    xmlUrl: "https://joanwestenberg.com/blog?format=rss",
    htmlUrl: "https://joanwestenberg.com/",
  },
  {
    text: "Techdirt",
    xmlUrl: "https://www.techdirt.com/techdirt_rss.xml",
    htmlUrl: "https://www.techdirt.com/",
  },
  {
    author: "Terence Eden",
    tag: "indieweb",
    xmlUrl: "https://shkspr.mobi/blog/feed/atom/",
    htmlUrl: "https://shkspr.mobi/blog",
  },
  {
    text: "The Dig",
    author: "Francine McKenna",
    authorWiki: "Francine McKenna",
    tags: ["crypto", "finance", "newsletter", "Substack"],
    xmlUrl: "https://thedig.substack.com/feed",
    htmlUrl: "https://thedig.substack.com/",
  },
  {
    text: "The Future, Now and Then",
    author: "Dave Karpf",
    tags: ["newsletter", "Substack", "technology"],
    xmlUrl: "https://davekarpf.substack.com/feed",
    htmlUrl: "https://davekarpf.substack.com/",
  },
  {
    text: "The History of the Web",
    author: "Jay Hoffmann",
    tags: ["web"],
    xmlUrl: "https://thehistoryoftheweb.com/feed/",
    htmlUrl: "https://thehistoryoftheweb.com/",
  },
  {
    text: "The Popehat Report",
    author: "Ken White",
    authorWiki: "Popehat",
    tags: ["law", "newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/6QXMLvJf2y.xml",
    htmlUrl: "https://www.popehat.com/",
  },
  {
    text: "The Present Age",
    author: "Parker Molloy",
    authorWiki: "Parker Molloy",
    tags: ["politics", "newsletter", "Substack"],
    xmlUrl: "https://www.readtpa.com/feed",
    htmlUrl: "https://www.readtpa.com/",
  },
  {
    text: "The Wikipedian",
    author: "William Beutler",
    tags: ["newsletter", "Substack", "Wikipedia"],
    xmlUrl: "https://thewikipedian.substack.com/feed",
    htmlUrl: "https://www.thewikipedian.net/",
  },
  {
    text: "This Week in the IndieWeb",
    tags: ["aggregator", "indieweb"],
    xmlUrl: "https://indieweb.org/this-week/feed.xml",
    htmlUrl: "https://indieweb.org/this-week",
  },
  {
    text: "Today in Tabs",
    author: "Rusty Foster",
    authorWiki: "Rusty Foster",
    tags: ["newsletter"],
    xmlUrl: "https://rss.beehiiv.com/feeds/ZRiesnGI0u.xml",
    htmlUrl: "https://www.todayintabs.com/",
  },
  {
    text: "Untangled",
    author: "Charley Johnson",
    tags: ["newsletter", "Substack", "technology"],
    xmlUrl: "https://untangled.substack.com/feed",
    htmlUrl: "https://untangled.substack.com/",
  },
  {
    text: "Waxy.org",
    author: "Andy Baio",
    authorWiki: "Andy Baio",
    tags: ["web"],
    xmlUrl: "https://waxy.org/feed/",
    htmlUrl: "https://waxy.org",
  },
  {
    text: "Writings and rehearsals by Nathan Schneider",
    author: "Nathan Schneider",
    authorWiki: "Nathan Schneider",
    xmlUrl: "https://nathanschneider.info/feed/",
    htmlUrl: "https://nathanschneider.info/",
  },
];
