module.exports = [
  {
    text: "Banned In Your State",
    author: "Laura Jedeed",
    tags: ["Substack"],
    xmlUrl: "https://www.bannedinyourstate.com/feed",
    htmlUrl: "https://www.bannedinyourstate.com/",
  },
  {
    text: "Blood in the Machine",
    author: "Brian Merchant",
    authorWiki: "Brian Merchant",
    tags: ["technology", "Substack"],
    xmlUrl: "https://www.bloodinthemachine.com/feed",
    htmlUrl: "https://www.bloodinthemachine.com/",
  },
  {
    text: "Dirty Bubble Media",
    author: "James Block",
    tags: ["crypto", "Substack"],
    xmlUrl: "https://www.dirtybubblemedia.com/feed",
    htmlUrl: "https://www.dirtybubblemedia.com/",
  },
  {
    text: "Disconnect",
    author: "Paris Marx",
    authorWiki: "Paris Marx",
    tags: ["technology"],
    xmlUrl: "https://disconnect.blog/rss/",
    htmlUrl: "https://disconnect.blog/",
  },
  {
    text: "Where's Your Ed At",
    author: "Ed Zitron",
    tags: ["technology"],
    xmlUrl: "https://www.wheresyoured.at/rss/",
    htmlUrl: "https://www.wheresyoured.at/",
  },
  {
    text: "Flaming Hydra",
    xmlUrl: "https://flaminghydra.com/rss/",
    htmlUrl: "https://flaminghydra.com/",
  },
  {
    text: "Garbage Day",
    author: "Ryan Broderick",
    authorWiki: "Ryan Broderick",
    xmlUrl: "https://rss.beehiiv.com/feeds/owMwaGYU36.xml",
    htmlUrl: "https://www.garbageday.email/",
  },
  {
    text: "Horrific/Terrific",
    author: "Georgia Iacovou",
    tags: ["Substack"],
    xmlUrl: "https://www.horrific-terrific.tech/feed",
    htmlUrl: "https://www.horrific-terrific.tech",
  },
  {
    text: "@Westenberg",
    author: "Joan Westenberg",
    xmlUrl: "https://www.joanwestenberg.com/rss/",
    htmlUrl: "https://www.joanwestenberg.com/",
  },
  {
    text: "Law Dork",
    author: "Chris Geidner",
    authorWiki: "Chris Geidner",
    tags: ["law", "Substack"],
    xmlUrl: "https://www.lawdork.com/feed",
    htmlUrl: "https://www.lawdork.com",
  },
  {
    text: "Men Yell at Me",
    author: "Liz Lenz",
    tags: ["Substack"],
    xmlUrl: "https://lyz.substack.com/feed",
    htmlUrl: "https://lyz.substack.com/",
  },
  {
    text: "Mind and Iron",
    author: "Steven Zeitchik",
    tags: ["Substack", "technology"],
    xmlUrl: "https://mindandiron.substack.com/feed",
    htmlUrl: "https://mindandiron.substack.com/",
  },
  {
    text: "Popular Information",
    tags: ["Substack"],
    xmlUrl: "https://popular.info/feed",
    htmlUrl: "https://popular.info/",
  },
  {
    text: "Read Max",
    author: "Max Read",
    tags: ["Substack"],
    xmlUrl: "https://maxread.substack.com/feed/",
    htmlUrl: "https://maxread.substack.com/",
  },
  {
    text: "Squishy Computer",
    tags: ["technology", "Substack"],
    xmlUrl: "https://newsletter.squishy.computer/feed",
    htmlUrl: "https://newsletter.squishy.computer/",
  },
  {
    text: "Tedium",
    author: "Ernie Smith",
    xmlUrl: "https://feed.tedium.co/",
    htmlUrl: "https://tedium.co/",
  },
  {
    text: "The Chancery Daily",
    tags: ["law", "Substack"],
    xmlUrl: "https://thechancerydaily.substack.com/feed",
    htmlUrl: "https://thechancerydaily.substack.com/",
  },
  {
    text: "The Dig",
    author: "Francine McKenna",
    authorWiki: "Francine McKenna",
    tags: ["finance", "Substack"],
    xmlUrl: "https://thedig.substack.com/feed",
    htmlUrl: "https://thedig.substack.com/",
  },
  {
    text: "The Future, Now and Then",
    author: "Dave Karpf",
    tags: ["Substack"],
    xmlUrl: "https://davekarpf.substack.com/feed",
    htmlUrl: "https://davekarpf.substack.com/",
  },
  {
    text: "The Handbasket",
    author: "Marisa Kabas",
    xmlUrl: "https://rss.beehiiv.com/feeds/40ZQ7CSldT.xml",
    htmlUrl: "https://www.thehandbasket.co/",
  },
  {
    text: "The Hypothesis",
    author: "Annalee Newitz",
    authorWiki: "Annalee Newitz",
    xmlUrl: "https://buttondown.com/thehypothesis/rss",
    htmlUrl: "https://buttondown.com/thehypothesis",
  },
  {
    text: "The Popehat Report",
    author: "Ken White",
    authorWiki: "Popehat",
    tags: ["law"],
    xmlUrl: "https://rss.beehiiv.com/feeds/6QXMLvJf2y.xml",
    htmlUrl: "https://www.popehat.com/",
  },
  {
    text: "The Present Age",
    author: "Parker Molloy",
    authorWiki: "Parker Molloy",
    tags: ["Substack"],
    xmlUrl: "https://www.readtpa.com/feed",
    htmlUrl: "https://www.readtpa.com/",
  },
  {
    text: "The Sword And the Sandwich",
    author: "Talia Lavin",
    authorWiki: "Talia Lavin",
    xmlUrl: "https://buttondown.com/theswordandthesandwich/rss",
    htmlUrl: "https://buttondown.com/theswordandthesandwich",
  },
  {
    text: "The Torment Nexus",
    author: "The Torment Nexus",
    xmlUrl: "https://torment-nexus.mathewingram.com/rss/",
    htmlUrl: "https://torment-nexus.mathewingram.com/",
  },
  {
    text: "The Wikipedian",
    author: "William Beutler",
    tags: ["Substack", "Wikipedia"],
    xmlUrl: "https://thewikipedian.substack.com/feed",
    htmlUrl: "https://www.thewikipedian.net/",
  },
  {
    text: "Today in Tabs",
    author: "Rusty Foster",
    authorWiki: "Rusty Foster",
    xmlUrl: "https://rss.beehiiv.com/feeds/ZRiesnGI0u.xml",
    htmlUrl: "https://www.todayintabs.com/",
  },
  {
    text: "Untangled",
    author: "Charley Johnson",
    tags: ["technology"],
    xmlUrl: "https://untangled.substack.com/feed",
    htmlUrl: "https://untangled.substack.com/",
  },
];
